services:
  # --------------------
  # Blue App
  # --------------------
  app_blue:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_blue
    ports:
      - "8081:3000"  
    environment:
      - X_APP_POOL=blue
      - X_RELEASE_ID=blue-v1
    volumes:
      - nginx_logs:/var/log/nginx

  # --------------------
  # Green App
  # --------------------
  app_green:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_green
    ports:
      - "8082:3000"
    environment:
      - X_APP_POOL=green
      - X_RELEASE_ID=green-v1
    volumes:
      - nginx_logs:/var/log/nginx

  # --------------------
  # Nginx Reverse Proxy
  # --------------------
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app_blue
      - app_green
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}

  # --------------------
  # Alert Watcher
  # --------------------
  alert_watcher:
    build: ./watcher
    container_name: alert_watcher
    working_dir: /watcher
    command: python3 watcher.py
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ACTIVE_POOL=${ACTIVE_POOL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD}
      - WINDOW_SIZE=${WINDOW_SIZE}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC}
    volumes:
      - ./watcher:/watcher
      - nginx_logs:/var/log/nginx:ro
    depends_on:
      - nginx
      - app_blue
      - app_green

volumes:
  nginx_logs:
